version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet restore .src/
      - run: dotnet build  .src/
      - run: dotnet run  .src/
