version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: cd src
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet run
